### PR TITLE
Improve name sanitization

### PR DESCRIPTION
**Pull request by rubellyte**
Removes multiple whitespace and non-ascii characters. Truncates names to a maximum of twenty characters in length. If name contains no valid characters, player is assigned the first four characters of their UUID as an alias.

### CODE REVIEW

**Comment by rubellyte** [comment]
This should fix #18.

**Comment by kharidiron** [comment]
As you are calling the `_clean_name()` function from outside of the class where it is local-to, you should remove the `_` from in front of its name. Why python does not force strong-typing, it is important to try and stay consistent in code-style.

**Comment by kharidiron** [comment]
Specifically I'm looking at line 191 of the file `general_commands.py`

**Comment by kharidiron** [comment]
Excellent. I'll merge this in.

**Pull request merged**
